apiVersion: v1
kind: Pod
metadata:
  name: kafka-admin
spec:
  restartPolicy: Never
  containers:
  - name: kafka-admin
    image: docker.io/bitnami/kafka:3.9.0-debian-12-r10
    command: ["bash", "-c"]
    args:
      - >
        echo "security.protocol=SASL_PLAINTEXT" > /tmp/kafka-client.properties &&
        echo "sasl.mechanism=PLAIN" >> /tmp/kafka-client.properties &&
        echo "sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"user1\" password=\"zRycaPH3fQ\";" >> /tmp/kafka-client.properties &&
        kafka-topics.sh --create --topic orders --partitions 3 --replication-factor 3 --bootstrap-server xp-flask-postgres-kafka.default.svc.cluster.local:9092 --command-config /tmp/kafka-client.properties