apiVersion: v1
kind: Secret
metadata:
  name: xp-flask-postgres-secrets
type: Opaque
data:
  POSTGRES_DATABASE: cG9zdGdyZXMtZGF0YWJhc2U=
  POSTGRES_USER: cG9zdGdyZXMtdXNlcm5hbWU=
  POSTGRES_PASSWORD: cG9zdGdyZXMtcGFzc3dvcmQ=
  KAFKA_SASL_USERNAME: dXNlcjE=