apiVersion: v1
kind: Service
metadata:
  name: xp-flask-postgres-service
spec:
  selector:
    app: xp-flask-postgres
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer